services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Australia/Adelaide'
      FTLCONF_webserver_api_password: "${PIHOLE_API_PASSWORD}"
    volumes:
      - 'pihole:/etc/pihole'
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.rule=Host(`pihole.${DOMAIN}`)"
      - "traefik.http.routers.pihole.entrypoints=websecure"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.services.pihole.loadbalancer.server.port=443"
      - "traefik.http.routers.pihole.service=pihole"
      - "traefik.http.routers.pihole.tls=true"

networks:
  proxy:
    external: true

volumes:
  pihole: