api:
  dashboard: true
  debug: true
  insecure: true

entrypoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
    https:
      address: ":443"
      http:
        tls:
          certResolver: "letsEncrypt"
          domains:
            - ${domain}

certificateResolver:
  letsEncrypt:
    acme:
      storage: "acme.json"
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    entrypoint: "unix///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    network: proxy
  file:
    filename: /config.yaml
    watch: true

accessLoh: {}
