api:
  dashboard: true
  debug: true
  insecure: true

entrypoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: ":443"
    http:
      tls:
        certResolver: "letsEncrypt"
        domains:
          - main: "${DOMAIN}"
            sans: "*.${DOMAIN}"

certificateResolver:
  letsEncrypt:
    acme:
      storage: "acme.json"
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      email: ${CF_API_EMAIL}
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - "9.9.9.9:53"
          - "1.1.1.1:53"

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    network: proxy
  file:
    filename: /config.yaml
    watch: true

accessLog: {}
