services:
  tunnel:
    container_name: "tunnel"
    image: cloudflare/cloudflared:latest
    command: tunnel run --token ${TOKEN}
    networks: 
      - public-tunnel

networks:
  public-tunnel:
    name: public-tunnel