services:
  portainer:
    container_name: "portainer"
    image: portainer/portainer-ce:latest
    ports:
      - 9000:9000
      - 9443:9443
    networks:
      proxy:
        aliases:
          - "portainer.${DOMAIN}"
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    env_file:
      - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.${DOMAIN}`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.service=portainer"
      - "traefik.http.routers.portainer.tls=true"

volumes:
  portainer-data:


networks:
  proxy:
    external: true
