api:
  dashboard: true
  debug: true
  insecure: true

entrypoints:
  web:
    address: ":80"
    http2:
      maxConcurrentStreams: 250
    http3: {}
    http:
      redirections:
        entrypoints:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    asDefault: true
    http2:
      maxConcurrentStreams: 250
    http3: {}
    http:
      tls:
        certResolver: "letsEncrypt"
        domains:
          - main: "${DOMAIN}"
            sans: "*.${DOMAIN}"
  webext:
    address: ":81"
    http2:
      maxConcurrentStreams: 250
    http3: {}
    http:
      redirections:
        entrypoints:
          to: webextsecure
          scheme: https
  webextsecure:
    address: ":444"
    asDefault: true
    http2:
      maxConcurrentStreams: 250
    http3: {}
    http:
      tls:
        certResolver: "letsEncrypt"
        domains:
          - main: "${DOMAIN}"
            sans: "*.${DOMAIN}"

certificateResolver:
  letsEncrypt:
    acme:
      storage: "acme.json"
      caServer: "LE_URL"
      email: "${CF_API_EMAIL}"
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
        resolvers:
          - "9.9.9.9:53"
          - "1.1.1.1:53"

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    endpoint: "unix///var/run/docker.sock"
    exposedByDefault: false
    watch: true
    network: proxy
  file:
    filename: /config/config.yaml
    watch: true

accessLog: {}
